# -*- coding: utf-8 -*-
"""soal1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVHOgSXUBQEnAc4aQrsxb25GXVKHAnW3
"""

import numpy as np
import matplotlib.pyplot as plt

class Segitiga:
    def __init__(self, alpha, beta, gamma):
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma

    def hitung(self, x):
        if x <= self.alpha:
            return 0
        elif self.alpha < x <= self.beta:
            return (x - self.alpha) / (self.beta - self.alpha)
        elif self.beta < x <= self.gamma:
            return (self.gamma - x) / (self.gamma - self.beta)
        else:
            return 0

class Trapesium:
    def __init__(self, alpha, beta, gamma, delta):
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.delta = delta

    def hitung(self, x):
        if x <= self.alpha:
            return 0
        elif self.alpha < x <= self.beta:
            return (x - self.alpha) / (self.beta - self.alpha)
        elif self.beta < x <= self.gamma:
            return 1
        elif self.gamma < x <= self.delta:
            return (self.delta - x) / (self.delta - self.gamma)
        else:
            return 0

class SFunction:
    def __init__(self, alpha, beta, gamma):
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma

    def hitung(self, x):
        if x <= self.alpha:
            return 0
        elif self.alpha < x <= self.beta:
            return 2 * ((x - self.alpha) / (self.gamma - self.alpha)) ** 2
        elif self.beta < x <= self.gamma:
            return 1 - 2 * ((x - self.gamma) / (self.gamma - self.alpha)) ** 2
        else:
            return 1

class GaussianFunction:
    def __init__(self, m, sigma):
        self.m = m
        self.sigma = sigma

    def hitung(self, x):
        return np.exp(-((x - self.m) ** 2) / (2 * self.sigma ** 2))

def plot_nilai():
    x = np.linspace(0, 4.0, 100)

    rendah = Segitiga(0, 0, 2)
    sedang = Segitiga(1.5, 2.5, 3.5)
    tinggi = Segitiga(3, 4, 4)

    miu_rendah = np.array([rendah.hitung(xi) for xi in x])
    miu_sedang = np.array([sedang.hitung(xi) for xi in x])
    miu_tinggi = np.array([tinggi.hitung(xi) for xi in x])

    plt.figure(figsize=(7, 5))
    plt.plot(x, miu_rendah, label='rendah', color='blue')
    plt.plot(x, miu_sedang, label='sedang', color='orange')
    plt.plot(x, miu_tinggi, label='tinggi', color='green')

    plt.xlabel("Nilai")
    plt.ylabel("Membership")
    plt.title("Himpunan Fuzzy untuk variabel nilai")
    plt.legend()
    plt.show()
plot_nilai()

def plot_pendapatan():
    x = np.linspace(0, 20.0, 100)

    rendah = Trapesium(0, 0, 2.5, 4)
    sedang = Trapesium(2, 6, 9, 13)
    tinggi = Trapesium(10, 13, 20, 20)

    miu_rendah = np.array([rendah.hitung(i) for i in x])
    miu_sedang = np.array([sedang.hitung(i) for i in x])
    miu_tinggi = np.array([tinggi.hitung(i) for i in x])

    plt.plot(x, miu_rendah, label='rendah', color='blue')
    plt.plot(x, miu_sedang, label='cukup', color='orange')
    plt.plot(x, miu_tinggi, label='tinggi', color='green')

    plt.xlabel("Pendapatan Orang Tua")
    plt.ylabel("Membership")
    plt.title("Himpunan Fuzzy untuk variabel pendapatan")
    plt.legend()
    plt.show()

plot_pendapatan()

def L(x, alpha, beta):
    if x <= alpha:
        return 1.0
    elif x <= beta:
        return (beta - x) / (beta - alpha)
    else:
        return 0.0

def R(x, alpha, beta):
    if x <= alpha:
        return 0.0
    elif x <= beta:
        return (x - alpha) / (beta - alpha)
    else:
        return 1.0

x = np.linspace(0, 3, 200)
miu_sedikit = np.zeros_like(x)
miu_banyak = np.zeros_like(x)

for i in range(len(x)):
    miu_sedikit[i] = L(x[i], 1, 2)
    miu_banyak[i] = R(x[i], 1, 2)

# Plot grafik
plt.plot(x, miu_sedikit, label='sedikit', color='blue')
plt.plot(x, miu_banyak, label='banyak', color='orange')
plt.xlabel("beasiswa")
plt.ylabel("Membership")
plt.title("Himpunan Fuzzy untuk variabel beasiswa")
plt.legend()
plt.show()

def fuzzifikasi_nilai(nilai):
    rendah = Segitiga(0, 0, 2)
    sedang = Segitiga(1.5, 2.5, 3.5)
    tinggi = Segitiga(3, 4, 4)

    miu_rendah = rendah.hitung(nilai)
    miu_sedang = sedang.hitung(nilai)
    miu_tinggi = tinggi.hitung(nilai)

    return {
        'rendah': miu_rendah,
        'sedang': miu_sedang,
        'tinggi': miu_tinggi
    }

def fuzzifikasi_pendapatan(pendapatan):
    rendah = Trapesium(0, 0, 2.5, 4)
    sedang = Trapesium(2, 6, 9, 13)
    tinggi = Trapesium(10, 13, 20, 20)

    miu_rendah = rendah.hitung(pendapatan)
    miu_sedang = sedang.hitung(pendapatan)
    miu_tinggi = tinggi.hitung(pendapatan)

    return {
        'rendah': miu_rendah,
        'sedang': miu_sedang,
        'tinggi': miu_tinggi
    }

def evaluasi_aturan(nilai_fuzz, pendapatan_fuzz):
    rule1 = min(nilai_fuzz['rendah'], pendapatan_fuzz['rendah'])
    rule2 = min(nilai_fuzz['sedang'], pendapatan_fuzz['sedang'])
    rule3 = min(nilai_fuzz['tinggi'], pendapatan_fuzz['sedang'])
    rule4 = min(nilai_fuzz['tinggi'], pendapatan_fuzz['rendah'])

    hasil_sedikit = max(rule1, rule2, rule3)
    hasil_banyak = rule4

    return hasil_sedikit, hasil_banyak

def defuzzifikasi_centroid(x_beasiswa, miu_sedikit, miu_banyak, hasil_sedikit, hasil_banyak):
    miu_gabungan = np.zeros_like(x_beasiswa)

    for i in range(len(x_beasiswa)):
        truncated_sedikit = min(miu_sedikit[i], hasil_sedikit)
        truncated_banyak = min(miu_banyak[i], hasil_banyak)
        miu_gabungan[i] = max(truncated_sedikit, truncated_banyak)

    if sum(miu_gabungan) == 0:
        return 0

    numerator = sum(x_beasiswa * miu_gabungan)
    denominator = sum(miu_gabungan)

    return numerator / denominator

def run_fuzzy_inference(nilai, pendapatan):
    print(f"Input: Nilai = {nilai}, Pendapatan = {pendapatan}")

    nilai_fuzz = fuzzifikasi_nilai(nilai)
    pendapatan_fuzz = fuzzifikasi_pendapatan(pendapatan)

    print("\nHasil Fuzzifikasi:")
    print(f"Nilai: rendah={nilai_fuzz['rendah']:.2f}, sedang={nilai_fuzz['sedang']:.2f}, tinggi={nilai_fuzz['tinggi']:.2f}")
    print(f"Pendapatan: rendah={pendapatan_fuzz['rendah']:.2f}, sedang={pendapatan_fuzz['sedang']:.2f}, tinggi={pendapatan_fuzz['tinggi']:.2f}")

    hasil_sedikit, hasil_banyak = evaluasi_aturan(nilai_fuzz, pendapatan_fuzz)

    x_beasiswa = np.linspace(0, 3, 200)
    miu_sedikit = np.zeros_like(x_beasiswa)
    miu_banyak = np.zeros_like(x_beasiswa)
    for i in range(len(x_beasiswa)):
        miu_sedikit[i] = L(x_beasiswa[i], 1, 2)
        miu_banyak[i] = R(x_beasiswa[i], 1, 2)

    print("\nHasil Evaluasi Aturan:")
    print(f"Beasiswa Sedikit (μ) = {hasil_sedikit:.2f}")
    print(f"Beasiswa Banyak (μ) = {hasil_banyak:.2f}")
    hasil_beasiswa = defuzzifikasi_centroid(x_beasiswa, miu_sedikit, miu_banyak, hasil_sedikit, hasil_banyak)
    print(f"\nHasil Defuzzifikasi (Metode Centroid): {hasil_beasiswa:.2f}")
    print(f"\nHasil Defuzzifikasi (Metode Centroid): {hasil_beasiswa:.2f}")

    plt.figure(figsize=(10, 6))
    plt.plot(x_beasiswa, miu_sedikit, 'b--', label='Beasiswa Sedikit')
    plt.plot(x_beasiswa, miu_banyak, 'g--', label='Beasiswa Banyak')

    truncated_sedikit = np.minimum(miu_sedikit, np.ones_like(miu_sedikit) * hasil_sedikit)
    truncated_banyak = np.minimum(miu_banyak, np.ones_like(miu_banyak) * hasil_banyak)

    plt.fill_between(x_beasiswa, truncated_sedikit, alpha=0.3, color='blue')
    plt.fill_between(x_beasiswa, truncated_banyak, alpha=0.3, color='green')

    plt.axvline(x=hasil_beasiswa, color='red', linestyle='-', label=f'Hasil ({hasil_beasiswa:.2f})')
    plt.xlabel('Beasiswa')
    plt.ylabel('Membership')
    plt.title('Hasil Inferensi Fuzzy Mamdani')
    plt.legend()
    plt.grid()
    plt.show()

    return hasil_beasiswa
hasil = run_fuzzy_inference(3.5, 2.5)